[wip] start porting classifyarray
EcoJulia/NeutralLandscapes.jl pull request #10
Opened 2021-02-11 21:17 UTC by mkborregaard

2021-02-11 21:22 UTC, mkborregaard commented on src/classifyarray.jl
> +    boundaryValues = sort(vec(maskedarray))[boundaryIndexes]
there are two full copies in this function - it must be possible to avoid at least this one

2021-02-11 21:49 UTC, mkborregaard commented
Just realized that `calcboundaries` is just `quantile`, though a little bit faster:

```julia
using StatsBase
a,c = rand(1000, 1000), [0.2, 0.4, 0.7, 0.8, 1]

julia> @btime quantile(vec(a), c)
  98.238 ms (5 allocations: 7.63 MiB)
5-element Vector{Float64}:
 0.20055273960046652
 0.40035575057383455
 0.7008467088240219
 0.8006453000863003
 0.9999981820198582

julia> @btime calcBoundaries(a, c)
  72.043 ms (7 allocations: 7.63 MiB)
5-element Vector{Float64}:
 0.2005524615247647
 0.40035544743228324
 0.7008461304132632
 0.8006452681104108
 0.9999981820198582

2021-02-12 01:43 UTC, tpoisot commented
Isn't it because `quantile` is doing some checks internally that `calcBoundaries` doesn't? I'm more than willing to pay the 20ms penalty on a 10⁶ grid if the result is safer.

2021-02-12 06:20 UTC, mkborregaard commented
Yes totally agree. It was just fun that it took me several readings of the code - and a port PR - to realize that this functionality already exists and has a name :-)

2021-02-12 06:21 UTC, mkborregaard commented
But I just need to check out that quantile behaves as expected in the presences of NaNs

2021-02-14 15:04 UTC, tpoisot commented
So, if `calcboundaries` is `quantiles`, shouldn't it an overload of `quantiles` instead?

2021-02-14 17:07 UTC, mkborregaard commented
I think this is ready to be reviewed now - though there are neither docs nor tests.

```julia
a = rand(DistanceGradient(rand(1:50*50, 10)), 50, 50);
plot(
    heatmap(a), 
    heatmap(classifyArray!(copy(a), [0.25, 1, 1, 1, 0.25, 0.5])), 
    size = (800, 300)
)
![class](https://user-images.githubusercontent.com/8429802/107883478-75f28800-6eef-11eb-8d66-fe614172c2cc.png)

2021-02-14 17:37 UTC, mkborregaard commented
Honestly I feel like I should just inline those two helper functions? They're not used anywhere else.

2021-02-14 18:58 UTC, tpoisot requested changes
Can you add an illustration to `docs/src/gallery.md`?

2021-02-14 19:00 UTC, tpoisot commented
> Honestly I feel like I should just inline those two helper functions? They're not used anywhere else.

I don't feel strongly about that - I might just rename them to start with `_` to give a little hint that they're really not user-facing, but otherwise it doesn't really matter.

2021-02-14 19:31 UTC, mkborregaard commented
Done. How de we feel about the camelCase? I'm almost inclined to just call it `classify!` though that sounds like something that could clash with other packages.

2021-02-14 19:41 UTC, tpoisot commented
I like `classify!` - maybe we don't export it?

2021-02-14 19:51 UTC, mkborregaard commented
Is `NeutralLandscapes.classify!` nicer than `classifyLandscape!`? 🤔

2021-02-14 20:27 UTC, mkborregaard commented
Hi @tpoisot I had a number of issues with conflict - I think I resolved them, but I had to rebase and force-push - hope you wont' get into trouble over at #22 which you branched from this.
I renamed to classify! and unexported - if that works let's merge this now. 
But actually as you can see in the example, the demolandscape function isn't actually that flexible, so it causes problems here - maybe it's better to go back to the raw code actually?

2021-02-15 01:40 UTC, rafaqz commented
We could just export `classify!`. I can't find other uses of it, and people can use import to avoid it if they need to?

2021-02-15 02:01 UTC, rafaqz approved these changes
Looks good to me. I use BlueStyle most of the time now so the camelCase is a bit confusing in terms of separating out types and variables, but that's another one for the style guide.

2021-02-15 02:01 UTC, rafaqz commented on src/classify.jl
> +function _w2cp(vec)
could inline this or give a clearer name, took me a while to figure out what it was

2021-02-15 07:43 UTC, merged

2021-02-15 07:44 UTC, mkborregaard commented
OK, I've exported it again (in the ecosystem only MLBase.jl appears to export a function of that name), and inline the two helper functions - and merged.

2021-02-15 19:58 UTC, tpoisot commented
great, I'll be able to deal with #22 (which doesn't need it yet anyways, but the NN cluster does)

2021-02-15 19:59 UTC, tpoisot commented
also in favor or not using `demolandscape` if it causes more issues than it solves